name: Update Catalog
on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  workflow_dispatch:
  push:
    paths: ['repositories.yaml']

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - name: Update visibility and generate catalog
        env:
          GH_TOKEN: ${{ secrets.ADMIN_PAT }}
        run: |
          # Note: Always use the official collab-sync from Broad Institute
          # Update visibility from GitHub
          uvx --from git+https://github.com/broadinstitute/collab-sync.git \
            collab-sync update

          # Generate catalog page
          uvx --from git+https://github.com/broadinstitute/collab-sync.git \
            collab-sync catalog

          # Commit only repositories.yaml changes if any (visibility updates)
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add repositories.yaml
          git diff --staged --quiet || git commit -m "Update repository visibility"
          git push

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Create gh-pages branch if it doesn't exist
          git checkout --orphan gh-pages || git checkout gh-pages

          # Remove all tracked files
          git rm -rf . || true

          # index.md is untracked, so it's still there
          # Just add and commit it
          git add index.md
          git commit -m "Update repository catalog" || true
          git push -f origin gh-pages